defaults:
  - algorithms: algorithms
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

mover_presets:
  - name: very-small
    width: 0.113
    length: 0.113
    height: 0.012
    mass: 0.6
  - name: small
    width: 0.127
    length: 0.127
    height: 0.012
    mass: 1
  - name: medium
    width: 0.155
    length: 0.155
    height: 0.012
    mass: 1.8

environment_parameter:
  - name: Movers
    prefix:
    parameters:
      - name: Collision shape safety margin
        code: offset
        hint: In meter
        type: float
        default: 0.0
      - name: Wall safety margin
        code: offset_wall
        hint: In meter
        type: float
        default: 0.0
      - name: Number of circles
        code: num_circles
        hint:
        type: int
        default: 40
      - name: Max Velocity
        code: v_max
        hint: In meter per second
        type: float
        default: 2.0
      - name: Max Acceleration
        code: a_max
        hint: In meter per second squared
        type: float
        default: 10.0
  - name: Objects
    prefix:
    parameters:
      - name: Min Mass
        code: min_mass
        hint: In kilograms
        type: float
        default: -1
      - name: Max Mass
        code: max_mass
        hint: In kilograms
        type: float
        default: -1
      - name: Min Friction
        code: min_friction
        hint:
        type: float
        default: -1
      - name: Max Friction
        code: max_friction
        hint:
        type: float
        default: -1
  - name: Jerk
    prefix:
    parameters:
      - name: Learn Jerk
        code: learn_jerk
        hint:
        type: boolean
        default: false
      - name: Max Jerk
        code: j_max
        hint: In meter per second to the power of three
        type: float
        default: 100.0